package com.hemoglobin.hemoglobin.models

class ProfileObjects(var Name: String,
                     var Email: String,
                     var Gender: String,
                     var Age: String,
                     var Weight: String,
                     var Place: String,
                     var Dob: String,
                     var Blood_Group: String,
                     var Hemoglobin_Level: String,
                     var Pulse_Rate: String,
                     var BP_Diastolic: String,
                     var Body_Temperature: String,
                     var Recent_Donation: String,
                     var Alcohol: String,
                     var HIV: String,
                     var Cardia_Arrest: String,
                     var Hyper_Tension: String,
                     var Kidney_Alignments: String,
                     var Diabetics: String,
                     var Epilepsy: String,
                     var Asthmatic: String,
                     var Tuberculosis: String,
                     var Jaundice: String,
                     var Tattoo: String,
                     var Cancer: String,
                     var BBP: String,
                     var TM: String,
                     var User_Id: String)